Stop-UDDashboard -port 8080
if ($i -eq $null){$i = 80}
$Colors = @{
    BackgroundColor = "#FF252525"
    FontColor = "#FFFFFFFF"
}
$inFile = Import-Csv '$PSScriptRoot\dash.csv' 
$targetCell = $inFile.Pie[0]
Write-Output $targetCell

<#
.SYNOPSIS
    Sample control for UniversalDashboard.
.DESCRIPTION
    Sample control function for UniversalDashboard. This function must have an ID and return a hash table.
.PARAMETER Id
    An id for the component default value will be generated by new-guid.
.EXAMPLE
    PS C:\> <example usage>
    Explanation of what the example does
.INPUTS
    Inputs (if any)
.OUTPUTS
    Output (if any)
.NOTES
    General notes
#>


Start-UDDashboard -port 8080 -Content { 
    New-UDDashboard  -Title "" -NavBarColor '#FF1c1c1c' -NavBarFontColor "#FF55b3ff" -BackgroundColor "#FF333333" -FontColor "#FFFFFFF" -Content { 

Start-UDRestApi -Endpoint $Endpoint       

New-UDRow -Columns { 

New-UDColumn -Size 12 {
New-UDGauge  -Value $targetCell -ValueText $targetCell - -NeedleColor "black" -Segments 10 -PaddingHorizontal 500 


}           

                New-UDColumn -Size 6 {

                New-UDChart -Title "This Month" -Type Line -AutoRefresh -RefreshInterval 7 @Colors -Endpoint {
                    
                    import-csv '$PSScriptRoot\This month.csv' | Out-UDChartData -LabelProperty "Row Labels" -DataProperty "Row Labels" -Dataset @(
                        
                        New-UDChartDataset -DataProperty "GPNA" -Label "GPNA" -BorderColor "#4D8B4EF3"-BackgroundColor "#4D8B4EF3"
                        New-UDChartDataset -DataProperty "REQS " -Label "REQS" -BorderColor '#4DF32ED2' -BackgroundColor '#4DF32ED2'
                        New-UDChartDataset -DataProperty "Inbox" -Label "Unread/Actionable Inbox" -BorderColor '#4D2EF348' -BackgroundColor '#4D2EF348'
                        New-UDChartDataset -DataProperty "Outstanding" -Label "Total Outstanding Actions" -BackgroundColor "#4DDC143C"
                        New-UDChartDataset -DataProperty "Todays Total" -Label "Total Today" -BorderColor '#4D57dfff' -BackgroundColor '#4D57dfff'

                    
                    )
                
                }}
                New-UDColumn -Size 6 {
                 New-UDChart -Title "This Week" -Type Line -AutoRefresh -RefreshInterval 7 @Colors -Endpoint {
                    
                    import-csv '$PSScriptRoot\This week.csv' | Out-UDChartData -LabelProperty "Row Labels" -DataProperty "Row Labels" -Dataset @(
                        
                        New-UDChartDataset -DataProperty "GPNA" -Label "GPNA" -BorderColor "#4D8B4EF3"-BackgroundColor "#4D8B4EF3"
                        New-UDChartDataset -DataProperty "REQS " -Label "REQS" -BorderColor '#4DF32ED2' -BackgroundColor '#4DF32ED2'
                        New-UDChartDataset -DataProperty "Inbox" -Label "Unread/Actionable Inbox" -BorderColor '#4D2EF348' -BackgroundColor '#4D2EF348'
                        New-UDChartDataset -DataProperty "Outstanding" -Label "Total Outstanding Actions" -BackgroundColor "#4DDC143C"
                        New-UDChartDataset -DataProperty "Todays Total" -Label "Total Today" -BorderColor '#4D57dfff' -BackgroundColor '#4D57dfff'

                    
                    )
                
                }}
                New-UDColumn -Size 6 {
                 New-UDChart -Title "Last Month" -Type Line -AutoRefresh -RefreshInterval 7 @Colors -Endpoint {
                    
                    import-csv '$PSScriptRoot\Last Month.csv' | Out-UDChartData -LabelProperty "Row Labels" -DataProperty "Row Labels" -Dataset @(
                        
                        New-UDChartDataset -DataProperty "GPNA" -Label "GPNA" -BorderColor "#4D8B4EF3"-BackgroundColor "#4D8B4EF3"
                        New-UDChartDataset -DataProperty "REQS " -Label "REQS" -BorderColor '#4DF32ED2' -BackgroundColor '#4DF32ED2'
                        New-UDChartDataset -DataProperty "Inbox" -Label "Unread/Actionable Inbox" -BorderColor '#4D2EF348' -BackgroundColor '#4D2EF348'
                        New-UDChartDataset -DataProperty "Outstanding" -Label "Total Outstanding Actions" -BackgroundColor "#4DDC143C"
                        New-UDChartDataset -DataProperty "Todays Total" -Label "Total Today" -BorderColor '#4D57dfff' -BackgroundColor '#4D57dfff'

                    
                    )
                
                }}
                New-UDColumn -Size 6 {
                   New-UDChart -Title "Last Week" -Type Line -AutoRefresh -RefreshInterval 7 @Colors -Endpoint {
                    
                    import-csv '$PSScriptRoot\Last Week.csv' | Out-UDChartData -LabelProperty "Row Labels" -DataProperty "Row Labels" -Dataset @(
                        
                        New-UDChartDataset -DataProperty "GPNA" -Label "GPNA" -BorderColor "#4D8B4EF3"-BackgroundColor "#4D8B4EF3"
                        New-UDChartDataset -DataProperty "REQS " -Label "REQS" -BorderColor '#4DF32ED2' -BackgroundColor '#4DF32ED2'
                        New-UDChartDataset -DataProperty "Inbox" -Label "Unread/Actionable Inbox" -BorderColor '#4D2EF348' -BackgroundColor '#4D2EF348'
                        New-UDChartDataset -DataProperty "Outstanding" -Label "Total Outstanding Actions" -BackgroundColor "#4DDC143C"
                        New-UDChartDataset -DataProperty "Todays Total" -Label "Total Today" -BorderColor '#4D57dfff' -BackgroundColor '#4D57dfff'

                    
                    )
                
                }
                }
    }        

            New-UDColumn -Size 6 {
                New-UDChart -Title "Outstanding Items Trending" -Type Line -AutoRefresh -RefreshInterval 7 @Colors -Endpoint {
                    
                    import-csv '$PSScriptRoot\changelog.csv' | Out-UDChartData -LabelProperty "Time" -DataProperty "Time" -Dataset @(
                        
                        New-UDChartDataset -DataProperty "GPNA Actions" -Label "GPNA Actions" -BorderColor "#4D8B4EF3"-BackgroundColor "#4D8B4EF3"
                        New-UDChartDataset -DataProperty "REQs" -Label "REQS" -BorderColor '#4DF32ED2' -BackgroundColor '#4DF32ED2'
                        New-UDChartDataset -DataProperty "Unread/Actionable Inbox" -Label "Unread/Actionable Inbox" -BorderColor '#4D2EF348' -BackgroundColor '#4D2EF348'
                        New-UDChartDataset -DataProperty "Total Outstanding Actions" -Label "Total Outstanding Actions" -BackgroundColor "#4DDC143C"
                        New-UDChartDataset -DataProperty "Total Today" -Label "Total Today" -BorderColor '#4D57dfff' -BackgroundColor '#4D57dfff'
                      )  }
                        }
      
    
    
    }
    }

